
// DISABLED: TABC_Create_Individual_Licenses_6:01
// comment('===> TABC Set Expiration Date - New');
// DISABLED: TABC_Create_Individual_Licenses_6:02
// currentMonth = fileDateObj.getMonth();
// DateTest= new Date();
// currentYear = DateTest.getFullYear();
// comment('===> Date Test '+DateTest.getFullYear());
// DISABLED: TABC_Create_Individual_Licenses_6:03
// nextYear = parseInt(fileDateObj.getYear()) + 2;
// nextYear2 = parseInt(fileDateObj.getYear()) + 3;
// comment('===> Year '+currentYear);
// DISABLED: TABC_Create_Individual_Licenses_6:04
// DateNew=dateAddMonths(null,12);
// comment('===> DateNew '+capId+'   '+DateNew);
// DISABLED: TABC_Create_Individual_Licenses_6:05
// if (appMatch('TNABC/Liquor by the Drink/Application/*')) {
// 	br_nch('TABC_Create_Individual_Licenses_8');
// 	licEditExpInfo('Active', DateSNew);
// 	}

// DISABLED: TABC_Create_Individual_Licenses_6:06
// if (appMatch('TNABC/Retail/Application/*') && !appMatch('TNABC/Retail/Application/Wine in Grocery Store')) {
// 	br_nch('TABC_Create_Individual_Licenses_8');
// 	licEditExpInfo('Active', DateSNew);
// 	}

// DISABLED: TABC_Create_Individual_Licenses_6:07
// if (appMatch('TNABC/Retail/Application/Wine in Grocery Store')) {
// 	licEditExpInfo('Active', DateNew);
// 	}

// DISABLED: TABC_Create_Individual_Licenses_6:08
// if (appMatch('TNABC/Supplier/Application/*')) {
// 	br_nch('TABC_Create_Individual_Licenses_8');
// 	licEditExpInfo('Active', DateSNew);
// 	}

