
// DISABLED: TABC_Create_Individual_Licenses_8:01
// if (currentMonth == 1) {
// 	DateSNew='12/31/' + currentYear;
// 	DateNew=dateAdd('12/31/' + nextYear,-1);
// 	}

// DISABLED: TABC_Create_Individual_Licenses_8:02
// if (currentMonth == 2) {
// 	DateSNew='12/31/' + currentYear;
// 	DateNew=dateAdd('12/31/' + nextYear,-1);
// 	}

// DISABLED: TABC_Create_Individual_Licenses_8:03
// if (currentMonth == 3) {
// 	DateSNew='12/31/' + currentYear;
// 	DateNew=dateAdd('12/31/' + nextYear,-1);
// 	}

// DISABLED: TABC_Create_Individual_Licenses_8:04
// if (currentMonth == 4) {
// 	DateSNew='12/31/' + currentYear;
// 	DateNew=dateAdd('12/31/' + nextYear,-1);
// 	}

// DISABLED: TABC_Create_Individual_Licenses_8:05
// if (currentMonth == 5) {
// 	DateSNew='12/31/' + currentYear;
// 	DateNew=dateAdd('12/31/' + nextYear,-1);
// 	}

// DISABLED: TABC_Create_Individual_Licenses_8:06
// if (currentMonth == 6) {
// 	DateSNew='12/31/' + currentYear;
// 	DateNew=dateAdd('12/31/' + nextYear,-1);
// 	}

// DISABLED: TABC_Create_Individual_Licenses_8:07
// if (currentMonth == 7) {
// 	DateSNew='12/31/' + currentYear;
// 	DateNew=dateAdd('12/31/' + nextYear,-1);
// 	}

// DISABLED: TABC_Create_Individual_Licenses_8:08
// if (currentMonth == 8) {
// 	DateSNew='12/31/' + currentYear;
// 	DateNew=dateAdd('12/31/' + nextYear,-1);
// 	}

// DISABLED: TABC_Create_Individual_Licenses_8:09
// if (currentMonth == 9) {
// 	DateSNew='12/31/' + currentYear;
// 	DateNew=dateAdd('12/31/' + nextYear,-1);
// 	}

// DISABLED: TABC_Create_Individual_Licenses_8:10
// if (currentMonth == 10) {
// 	DateSNew='12/31/' + currentYear;
// 	DateNew=dateAdd('12/31/' + nextYear,-1);
// 	}

// DISABLED: TABC_Create_Individual_Licenses_8:11
// if (currentMonth == 11) {
// 	DateSNew='12/31/' + currentYear;
// 	DateNew=dateAdd('12/31/' + nextYear,-1);
// 	}

// DISABLED: TABC_Create_Individual_Licenses_8:12
// if (currentMonth == 12) {
// 	DateSNew='12/31/' + currentYear;
// 	DateNew=dateAdd('12/31/' + nextYear,-1);
// 	}

