
// DISABLED: TABC_Create_Individual_Licenses_0:02
// LICcomm = 'Created from Application # ' + capIDString;
// comment(LICcomm);
// DISABLED: TABC_Create_Individual_Licenses_0:03
// if (appMatch('TNABC/Liquor by the Drink/Application/*')) {
// 	br_nch('TABC_Create_Individual_Licenses_1');
// 	}

// DISABLED: TABC_Create_Individual_Licenses_0:04
// if (appMatch('TNABC/Retail/Application/*')) {
// 	br_nch('TABC_Create_Individual_Licenses_1');
// 	}

// DISABLED: TABC_Create_Individual_Licenses_0:05
// if (appMatch('TNABC/Supplier/Application/*')) {
// 	br_nch('TABC_Create_Individual_Licenses_1');
// 	}

// DISABLED: TABC_Create_Individual_Licenses_0:06
// if (appMatch('TNABC/Wholesale/Application/*')) {
// 	br_nch('TABC_Create_Individual_Licenses_1');
// 	}

// DISABLED: TABC_Create_Individual_Licenses_0:07
// if (appMatch('TNABC/Permits/Application/*')) {
// 	br_nch('TABC_Create_Individual_Licenses_1');
// 	}

// DISABLED: TABC_Create_Individual_Licenses_0:08
// if (appMatch('TNABC/Education/Application/*')) {
// 	br_nch('TABC_Create_Individual_Licenses_1');
// 	}

